# Generated by Django 5.1 on 2024-11-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_userreg_c_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='Images',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
