# Generated by Django 5.1 on 2024-12-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_search_alter_userreg_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('Image', models.ImageField(null=True, upload_to='userimages')),
            ],
        ),
        migrations.DeleteModel(
            name='userreg',
        ),
    ]
